### ISSUE TITLE
FastHttp panic

### ISSUE THREAD

**Issue by MindHunter86** [MindHunter86/addie#105]
```
9:03PM INF runtime.go:292 > runtime config - applied lottery chance 100
9:04PM INF runtime.go:316 > runtime config - applied quality 1080
9:05PM INF runtime.go:252 > runtime config - blocklist status updated
panic: BUG: error in SetWriteDeadline(200ms): set tcp4 XXX:8089: use of closed network connection

goroutine 4191 [running]:
github.com/valyala/fasthttp.(*Server).serveConn(0xc0001c0200, {0xb4ce80?, 0xc000013ba0})
        github.com/valyala/fasthttp@v1.50.0/server.go:2380 +0x1f85
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0001c50e0, 0xc0000633a0)
        github.com/valyala/fasthttp@v1.50.0/workerpool.go:224 +0xa9
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
        github.com/valyala/fasthttp@v1.50.0/workerpool.go:196 +0x38
created by github.com/valyala/fasthttp.(*workerPool).getCh
        github.com/valyala/fasthttp@v1.50.0/workerpool.go:195 +0x1b0

```

**Comment by MindHunter86** [comment]
maybe problem in #100 

https://github.com/MindHunter86/addie/blob/master/app/app.go#L89-L93
